### ISSUE TITLE
btrfs headers issue with containerd for RHEL based distros

### ISSUE THREAD

**Issue by crazy-max** [docker/packaging#87]
Same as https://github.com/docker/packaging/pull/69#issuecomment-1374731078 (fyi @neersighted)

https://github.com/docker/packaging/actions/runs/4158235007/jobs/7193316373#step:7:655

```
#41 52.20 + bin/containerd
#41 52.20 go build  -gcflags=-trimpath=/go/src -buildmode=pie  -o bin/containerd -ldflags '-X github.com/containerd/containerd/version.Version=v0.0.0-20230212032334-040fcf8 -X github.com/containerd/containerd/version.Revision=040fcf85f0a7d88ef3d55720d9821c9cb127c81c -X github.com/containerd/containerd/version.Package=containerd.io -s -w ' -tags "urfave_cli_no_docs"  ./cmd/containerd
#41 81.49 # github.com/containerd/btrfs/v2
#41 81.49 In file included from vendor/github.com/containerd/btrfs/v2/btrfs.go:21:0:
#41 81.49 ./btrfs.h:19:2: error: #error "Headers from kernel >= 4.12 are required on compilation time (not on run time)"
#41 81.49  #error "Headers from kernel >= 4.12 are required on compilation time (not on run time)"
#41 81.49   ^
#41 81.49 In file included from vendor/github.com/containerd/btrfs/v2/btrfs.go:21:0:
#41 81.49 ./btrfs.h:22:30: fatal error: linux/btrfs_tree.h: No such file or directory
#41 81.49  #include <linux/btrfs_tree.h>
```

**Comment by neersighted** [comment]
Right, so this is because of https://github.com/containerd/containerd/pull/7933. However that change should only have gone into contianerd 1.7 -- what are we packaging in this repo?

containerd also has a build tag (`no_btfs`) that can be used here.

**Comment by crazy-max** [comment]
Tip top of the branch builds from the default branch for each packages so we are warned of required changes: https://github.com/docker/packaging/blob/9ddb8849eb3ab9a656984180ad03d0af18fe09c8/pkg/containerd/docker-bake.hcl#L22-L25

**Comment by neersighted** [comment]
Got it, I'd suggest putting in the same buildtags fix as the engine on the same OSes, I don't think any other action should be required.

**Comment by crazy-max** [comment]
Ah the build tag is already there actually but does not cover rhel 7: https://github.com/docker/packaging/blob/b2cdad2c7ec97af416a4015388f0ea51dc9e308b/pkg/containerd/rpm/containerd.spec#L112-L116
